Search feature and music player screen
ArielVerdugo/react-native-challenge pull request #1
Opened 2023-10-04 20:35 UTC by ArielVerdugo

This pr contains:

- Search feature: As a user, I want to search for a song, artist, or album title and see a list of search results to find a specific song. The list should display the results dynamically as the user types.
- Search layout
- Music player layout with song information

Screenshots:

![Captura de pantalla 2023-10-04 a la(s) 17 30 28](https://github.com/ArielVerdugo/react-native-challenge/assets/45951048/14a64972-7702-4a12-9117-a0795ef24378)

![Captura de pantalla 2023-10-04 a la(s) 17 30 39](https://github.com/ArielVerdugo/react-native-challenge/assets/45951048/8993059a-0b30-47a8-ae72-168a8fa81690)

2023-10-04 20:37 UTC, ArielVerdugo commented on src/screens/WIP/Search.js
> +    queryFn: () =>
In the next pr I will move this an controller file

2023-10-06 13:41 UTC, sebastianpaz requested changes

2023-10-06 13:41 UTC, sebastianpaz commented on android/app/src/main/java/com/reactnativecodechallenge/MainApplication.java
>  import com.facebook.react.ReactNativeHost;
I believe these changes are unrelated to the pull request, so please remove them from this commit and create a new pull request with these changes.

This happens to many `android/` and `ios/` file in this PR. This comment applies to all of them.

2023-10-06 13:41 UTC, sebastianpaz commented on ios/ReactNativeCodeChallenge-Bridging-Header.h
> +
Same

2023-10-06 13:41 UTC, sebastianpaz commented on ios/ReactNativeCodeChallenge.xcodeproj/project.pbxproj
> +						LastSwiftMigration = 1430;
Same

2023-10-06 13:41 UTC, sebastianpaz commented on ios/ReactNativeCodeChallenge.xcodeproj/project.pbxproj
> +				8D3BE3942ACDC0E1004EBFD0 /* dummy.swift in Sources */,
Same

2023-10-06 13:41 UTC, sebastianpaz commented on src/components/Navigation/SearchNavigator.js
> +        name={'Search'}
You don't need to write curly brackets `{ }` when your prop value is a string.
```suggestion
        name='Search'
```

2023-10-06 13:41 UTC, sebastianpaz commented on src/screens/WIP/Search.js
> +  };
You can simplify this logic without using conditional if/else.

Clue: use optional chaining `?`

2023-10-06 13:41 UTC, sebastianpaz commented on src/screens/WIP/Search.js
> +  };
Same here. Use optional chaining operator `?`

2023-10-06 13:41 UTC, sebastianpaz commented on src/screens/WIP/Search.js
> +          keyExtractor={(item, index) => index.toString()}
Never use _indexes_ are key extractors, since that breaks FlatList's recycling feature.
Use a real, unique `id` coming from the item.

2023-10-06 13:41 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +        console.log(error.message);
To enforce good UX practices, it would be nice to have a dialog telling the user that the song isn't available (and preferably a _Back_ button). As a general rule, please consider avoiding `console.logs` in production code.

2023-10-09 16:52 UTC, ArielVerdugo commented on android/app/src/main/java/com/reactnativecodechallenge/MainApplication.java
>  import com.facebook.react.ReactNativeHost;
After read documentation for install react-native-sound, these changes are necessary to work propertly

2023-10-10 16:46 UTC, merged