Play music screen
ArielVerdugo/react-native-challenge pull request #4
Opened 2023-10-17 17:34 UTC by ArielVerdugo

This pr contains:

- Layout play music screen
- Logic to stop and play songs
- Logic to rewind and fast forward song

Notes:

- There is a bug: when you need to stop a song the icon "Play" doesn't change. I will fix with the last pr.

2023-10-17 19:32 UTC, marinawangmw requested changes

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
> +  };
why is this jumping 10 seconds but the name of the function says 15?

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
>          isDarkTheme === true ? stylesDark.containerDark : styles.container
for it to be cleaner you can do 
```suggestion
        isDarkTheme ? stylesDark.containerDark : styles.container
```

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
> +      var time = seconds + secondsToJump;
use `let` instead of `var` here
```suggestion
      let time = seconds + secondsToJump;
```

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
> +            source={{uri: `${route.params.item.artwork}`}}
```suggestion
            source={{uri: route.params.item.artwork}}
```

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
>              isDarkTheme === true ? stylesDark.textTitleDark : styles.textTitle
```suggestion
            isDarkTheme ? stylesDark.textTitleDark : styles.textTitle
```

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
> +              source={sound.isPlaying() ? ForwardIcon : PlayIcon}
nice job!

2023-10-17 19:32 UTC, marinawangmw commented on src/screens/WIP/SongInfo.js
Why is the name of the folder `WIP`?

2023-10-19 20:35 UTC, ArielVerdugo commented on src/screens/WIP/SongInfo.js
> +  };
Nice catch!

2023-10-20 14:54 UTC, sebastianpaz approved these changes

2023-10-20 14:54 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +  };
```suggestion
  const jumpPrev10Seconds = () => {
    jumpSeconds(-JUMP_INTERVAL);
  };
  const jumpNext10Seconds = () => {
    jumpSeconds(JUMP_INTERVAL);
  };
```

2023-10-20 18:34 UTC, merged