[AM-5]: Sound bar layout and logic
ArielVerdugo/react-native-challenge pull request #5
Opened 2023-10-20 20:57 UTC by ArielVerdugo

This pr contains:

- Layout song bar
- Logic to play song with song bar

Notes:

- In the next pr I will change setInterval in song info screen for something more appropriate.

https://github.com/ArielVerdugo/react-native-challenge/assets/45951048/ce448010-e918-4a3a-8a3e-cea5b8c7394a

2023-10-23 11:35 UTC, sebastianpaz requested changes
Minor issues and important issues to address before merging

2023-10-23 11:35 UTC, sebastianpaz commented on package.json
> +    "react": "^18.2.0",
Why react was updated?

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  );
What's this?

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  const soundBar = useSelector(getSoundBar);
What are you getting here? (`getSoundBar` does not look descriptive to me).

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  const sound = soundBar[0]?.sound;
Same here. What's the purpose of this `sound` variable?

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  }
In which case the `duration` of a song is equal to `0`?

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  });
This is what we talked about `setInterval`. As spoken earlier, will be waiting for a PR that addresses this differently 💪🏻

2023-10-23 11:35 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  if (soundBar[0]?.show && index !== 1) {
I don't understand this `if` condition, what's the `show` variable for and what's the implication of `index !== 1`?
I'd suggest rewriting this line so I and others could better understand this condition without asking.

2023-10-23 11:35 UTC, sebastianpaz commented on src/redux/Reducer.js
> +  return arr;
Do not use **push**.
Remember that in Redux, foundationally, we should not return the same state object modified, but a **new** state.

Use the spread operator here.

2023-10-23 11:35 UTC, sebastianpaz commented on src/redux/SoundBarSelector.js
> +  return Object.values(state.soundBarReducer);
Why `Object.values`? Isn't it easier to just return the `soundBar` object ?

2023-10-23 11:35 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +  var showSongBar = false;
Remember that this variable will not save this data and reset to `false` on every render, which may not be what you want..

2023-10-23 11:35 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +        artist: route.params.item.artist,
You can use object destructuring here.

2023-10-23 11:35 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +        show: showSongBar,
If you're calling an action called `showSoundBar` then why are you sending a `show` boolean parameter?

2023-10-23 11:35 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +  });
Same (interval)

2023-10-23 11:35 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +        show: showSongBar,
Are the `songBar` and `soundBar` concepts the same as each other? If they are, stick to a single name. Don't use both names, as it generates ambiguity.

2023-10-23 21:07 UTC, ArielVerdugo commented on src/screens/WIP/SongInfo.js
> +  var showSongBar = false;
I tryed to use a "useState" and pass this value like this: 
`dispatch(
      toggleSoundBar({
        trackName: trackName,
        preview: preview,
        artwork: artwork,
        artist: artist,
        sound: sound,
        showSoundBar: isPlaying,
      }),`

2023-10-24 18:44 UTC, sebastianpaz requested changes

2023-10-24 18:44 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  if (soundBar[0]?.show && index !== 1) {
```if (currentScreen !== PLAYER_SCREEN && isPlaying)```

2023-10-24 18:44 UTC, sebastianpaz commented on src/redux/Reducer.js
> +  return arr;
Please return an object instead of an array.

2023-10-24 18:44 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
>    }
Remember to use the callbacks of the library

2023-10-24 18:44 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
>          }
useInterval here

2023-10-24 18:44 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +        sound: sound,
Why are you dispatching `sound` here?

2023-10-24 18:44 UTC, sebastianpaz commented on src/screens/WIP/SongInfo.js
> +  let showSoundBar = false;
Remember what we've spoken about state here.

2023-10-24 18:44 UTC, sebastianpaz commented on src/redux/Reducer.js
> +        sound: sound,
```suggestion

```

2023-10-24 18:44 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +    state => state?.routes[0]?.state?.routes[4]?.state?.index,
This might be something you're still trying to fix, but just wanted to comment anyway for you to keep track of this

2023-10-24 18:44 UTC, sebastianpaz commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  const searchedSong = soundBarData?.sound;
`searchSong` refers to a specific use case where you've previously searched for the song before playing it, but that is not MusicPlayer's business. I'd suggest not using the term `searched` here.

2023-10-24 18:54 UTC, ArielVerdugo commented on src/screens/WIP/SongInfo.js
> +        sound: sound,
Beacuase I need to share this sound with MusicPlayer component for play it

2023-10-24 18:55 UTC, ArielVerdugo commented on src/components/Song/MusicPlayer/MusicPlayer.js
>    }
I deleted it!

2023-10-24 18:55 UTC, ArielVerdugo commented on src/components/Song/MusicPlayer/MusicPlayer.js
>          }
I deleted

2023-10-24 19:00 UTC, ArielVerdugo commented on src/screens/WIP/SongInfo.js
> +  let showSoundBar = false;
i wrote this message in the last code review about this comment:
I tried to use a "useState" to store if I need to show sound bar but when I need to check this value(Music player component) I don't have it immediately. The state updates will reflect in the next re-render.

2023-10-24 19:02 UTC, ArielVerdugo commented on src/redux/Reducer.js
> +        sound: sound,
I need to share this sound with the soundBar.

2023-10-24 19:03 UTC, ArielVerdugo commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +  const searchedSong = soundBarData?.sound;
perfect!

2023-10-24 19:12 UTC, ArielVerdugo commented on src/components/Song/MusicPlayer/MusicPlayer.js
> +    state => state?.routes[0]?.state?.routes[4]?.state?.index,
fixing!

2023-10-25 18:43 UTC, merged